# Site settings
title: Bruno Soares
url: 'http://bratomes.com.br'
baseurl: ''
google_analytics: 'UA-163450351-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Bruno Soares'
  email: brunomsss@gmail.com
  twitter_username: bratomes
  github_username:  bratomes
  linkedin_username:  bratomes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
paginate_path: '/pages/blog/page:num/'
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
